---
title: "Coursera Data Science Specialization - SwiftKey Capstone"
author: "JMSG"
date: "19 de agosto de 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Assignment
This is the final assignment of the Data Science Specialization offered by Coursera in cooperation with SwiftKey.

Tha main goal is to build a shiny app able to predict the next word based on the english files of the HC Corpora corpus. The corpus includes more than 3M of text lines coming from blogs, news and tweets. A sample is provided below with two sentences of each source.

- Blog 1: In the years thereafter, most of the Oil fields and platforms were named after pagan "gods".
- Blog 2: We love you Mr. Brown.
- News 1: He wasn't home alone, apparently.
- News 2: The St. Louis plant had to close.
- Twitter 1: Desk put together, room all set up. Oh boy, oh boy
- Twitter 2: I'm doing it!

## Methodological approach
The three english corpuses were generated by sampling and cleaning the original files. Exploratory analyses were done by tokenizing them into 2-4 grams and presented in the milestone report.

For the prediciton model the unigram was used as a dictionary while the trigram was used for training a Naive Bayes classifier, ending in three dictionaries and three prediction models, one for each source.

Once the sentence is introduced it is cleansed and each model predicts the next word, which are presented as three potential next words by the app.


## Performance
Due to space and processing limitations three samples were build.

- A large one with 2500 samples of blogs and news as well as 5000 of tweets. 

- A medium size one with 1250 samples of blogs and news as well as 2500 of tweets. 

- A small one with 250 samples of blogs and news as well as 500 of tweets. 

The performance of the model is around 4-6% in all cases, while the processing time increases significantly, so the small one is used in the shiny app.


## How it works
On the left corner you should insert the sentence and press enter or push the prediciton button.

On the right side you will see the sentence your introduced, the part used for the prediction as well as the three potential words, obtained from the blog, news and twitter corpus respectively. 

You can find the app and the source codes at my GitHub account.

app: https://josepmariasalanovagrau.shinyapps.io/coursera_data_science_specialization_-_swiftkey_capstone/

source code files: https://github.com/JosepMariaSalanovaGrau/Data_Science_Specialization-Capstone
